CREATE TABLE IF NOT EXISTS GENRES(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS AUTHORS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS BOOKS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(1000),
    RELEASE_YEAR INTEGER,
    AUTHOR_ID BIGINT REFERENCES AUTHORS (ID) ON DELETE CASCADE,
    GENRE_ID BIGINT REFERENCES GENRES (ID) ON DELETE CASCADE,
    UNIQUE (NAME, AUTHOR_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS BOOK_COMMENTS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEXT VARCHAR(1000) UNIQUE,
    BOOK_ID BIGINT REFERENCES BOOKS(ID)
);
