DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(1000),
    RELEASE_YEAR INTEGER,
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT);
