spring:
  output:
    ansi:
      enabled: always
  messages:
    basename: language/messages
    encoding: UTF-8

application:
  locale: ru_RU
  default-test-file-name: tests/StudentSimpleTest.csv
  file-names-by-locale:
    "ru_RU": tests/StudentSimpleTest_ru.csv
    "en": tests/StudentSimpleTest.csv
